# Site settings
title: Running Away
email: tanghaodong25@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  音乐学得不好的人都出来拍照了
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xiadiandian.site" # the base hostname & protocol for your site
twitter_username: xiadiandian
github_username:  xiadiandian

# Build settings
markdown: kramdown

paginate: 4

author: Xia Diandian

gems: [jekyll-paginate]
