# Site settings
title: Running Away
email: tanghaodong25@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xiadiandian.site" # the base hostname & protocol for your site
twitter_username: xiadiandian
github_username:  xiadiandian

# Build settings
markdown: kramdown

paginate: 4

author: Xia Diandian

gems: [jekyll-paginate]
